language: c

#   Install dependencies first
before_script:
- sudo apt-get install uuid-dev

- git clone git://github.com/jedisct1/libsodium.git
- git clone git://github.com/zeromq/libzmq.git
- git clone git://github.com/zeromq/czmq.git
- cd czmq && git checkout v2.2.0 && cd ..
- git clone git://github.com/zeromq/zyre.git
- for project in libsodium libzmq czmq zyre; do
-     cd $project
-     ./autogen.sh
-     ./configure && make check
-     sudo make install
-     sudo ldconfig
-     cd ..
- done

#   Build and check this project
script: ./autogen.sh && ./configure && make check
